title: Nassim Rostane # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Generation zero algerian immigrant with a passion for data science & analytics, AI/Machine learning and tech product management.
  <br><br>
  Emory University MBA.
  <br><br>
  During my career, I have worked for various manufacturing companies specializing in addressing intricate supply chain problems, ranging from optimization to cost forecasting.
  <br><br>
  I am also an avid gamer, you can find me playing RPGs/ARPGs and the occasional sandbox/survival games.
  <br><br>
  <a href="https://www.linkedin.com/in/nassim-rostane-0b792b135">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
